api-server: # 应用基本配置
  env: local # 环境名称
  port: 8888 # 服务监听端口号
  app-name: gin-app # 应用名称
  app-url: http://localhost # 应用域名

log:
  level: info # 日志等级
  root-dir: ./logs # 日志根目录
  filename: app.log # 日志文件名称
  format: # 写入格式 可选json
  show-line: true # 是否显示调用行
  max-backups: 3 # 旧文件的最大个数
  max-size: 500 # 日志文件最大大小（MB）
  max-age: 7 # 旧文件的最大保留天数
  compress: true # 是否压缩